<?php $this->layout('layout::default', ['title' => 'EGLi - Suchen']) ?>
<?php $this->push('stylesheet') ?>
<link href="/css/app/def-termin-search.css?u=<?= REFRESH_STATIC_FILES ?>" rel="stylesheet">
<?php $this->end() ?>
<?php $this->push('javascript') ?>
<script src="/js/app/def-termin-search.js?u=<?= REFRESH_STATIC_FILES ?>" type="module"></script>
<?php $this->end() ?>
<?php $this->insert('app-partial::___search', [
    'data' => $terminCollection,
    'redirectUrl' => $redirectUrl,
    'form' => $defTerminSearchForm,
    'datalist' => $datalist,
    'manage' => false,
]) ?>