<?php

use App\Enum\TerminStatusEnum;
use App\Service\HelperService;
use App\Service\UrlpoolService;

// init
$terminEntity = $terminEntity;

?>
<?php $this->layout('layout::default', ['title' => 'EGLi Show']) ?>
<?php $this->push('stylesheet') ?>
<?php $this->end() ?>
<?php if ($terminEntity) : ?>
    <?php
    $wrapperTag = TerminStatusEnum::GESTRICHEN->value === $terminEntity->getTerminStatus() ? ['del'] : [];
    ?>
    <?php if ($terminEntity->getTerminImage() && TerminStatusEnum::BILD->value === $terminEntity->getTerminStatus()): ?>
        <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center bg-dark"
             style="background-image: url('<?= $this->media($terminEntity->getTerminImage()) ?>'); background-repeat: no-repeat; background-size: contain; background-position: center;">
            <!-- <img class="img-fluid" style="margin: auto;" src="<?= $this->media($terminEntity->getTerminImage()) ?>" alt="<?= $this->media($terminEntity->getTerminBetreff()) ?>"> -->
        </div>
        <script>
            setTimeout(() => {
                window.scrollTo(0, document.body.scrollHeight)
            }, 3000);
        </script>
    <?php endif; ?>
    <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
        <div class="m-1 text-center" style="max-width: 1200px;">
            <?php $this->insert('partial::wrappertags', ['type' => 'open', 'tags' => $wrapperTag]); ?>
            <?php if ($terminEntity->getTerminStatus() === TerminStatusEnum::MITTEILUNG->value): ?>
                <figure>
                    <blockquote class="blockquote fs-1 fw-light">
                        <p><?= $this->escape($terminEntity->getTerminBetreff()) ?></p>
                        <?php if ($terminEntity->getTerminText()): ?>
                            <p><?= nl2br($this->escape($terminEntity->getTerminText())) ?></p>
                        <?php endif ?>
                    </blockquote>
                    <?php if ($terminEntity->getTerminMitvon()): ?>
                        <figcaption class="blockquote-footer fs-3">
                            <cite title="Source Title"><?= $this->escape($terminEntity->getTerminMitvon()) ?></cite>
                        </figcaption>
                    <?php endif; ?>
                </figure>
            <?php else: ?>
                <?php if ($terminEntity->getTerminImage() && TerminStatusEnum::BILD->value !== $terminEntity->getTerminStatus()): ?>
                    <img class="img-fluid mb-3" src="<?= $this->media($terminEntity->getTerminImage()) ?>?w=200"
                         alt="<?= $this->media($terminEntity->getTerminBetreff()) ?>">
                <?php endif ?>
                <?php if ($terminEntity->getTerminStatus() !== TerminStatusEnum::MITTEILUNG->value) : ?>
                    <h3 class="my-3 fw-light">
                        <?= HelperService::format_displayDate($terminEntity->getTerminDatumstart(), $terminEntity->getTerminDatumEnde()) ?>
                        <?php if (!$terminEntity->getTerminZeitGanztags() && $terminEntity->getTerminZeitstart()): ?>
                            - <?= HelperService::format_displayTime($terminEntity->getTerminZeitstart()) ?>
                        <?php endif; ?>
                    </h3>
                <?php endif; ?>
                <h1 class="fw-light">
                    <a class="link-body-emphasis text-decoration-none" href="/#<?= UrlpoolService::getAnchorString($terminEntity->getTerminDatumstart()) ?>">
                        <?= $this->escape($terminEntity->getTerminBetreff()) ?>
                    </a>
                </h1>
                <p>
                    <?php if ($terminEntity->getTerminMitvon()): ?>
                        <br>
                        <?php if ($terminEntity->getTerminStatus() === TerminStatusEnum::NORMAL->value): ?>
                            mit
                        <?php endif; ?>
                        <?= $this->escape($terminEntity->getTerminMitvon()) ?>
                    <?php endif; ?>
                    <?php if ($terminEntity->getTerminText()): ?>
                        <br>
                        <br>
                        <?= nl2br($this->escape($terminEntity->getTerminText())) ?>
                    <?php endif ?>
                    <?php if ($terminEntity->getTerminLabel() || $terminEntity->getTerminLink()) : ?>
                        <br>
                        <?php if ($terminEntity->getTerminLabel()) : ?>
                            <br><i class="bi bi-info-circle"></i> <?= $this->escape($terminEntity->getTerminLabel()) ?>
                        <?php endif; ?>
                        <?php if ($terminEntity->getTerminLink()): ?>
                            <br>
                            <a class="icon-link d-block text-decoration-none" href="<?= $terminEntity->getTerminLink() ?>">
                                <i class="bi bi-link"></i> <?= $this->escape($terminEntity->getTerminLinkTitel() ?? 'Link') ?>
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>
                </p>
            <?php endif; ?>
            <?php $this->insert('partial::wrappertags', ['type' => 'close', 'tags' => $wrapperTag]); ?>
        </div>
    </div>
<?php else : ?>
    <div class="alert alert-warning text-center my-3 fw-bold" role="alert">
        Es wurde kein Eintrag gefunden.
    </div>
<?php endif; ?>
