<?php

use App\Enum\TerminStatusEnum;
use App\Service\AttributeService;
use App\Service\HelperService;
use App\Service\UrlpoolService;
use JK\DTF\DTF;

// init
$termin = $data;
$event_nav = $manage ? '/manage/termin-grid' : '/';

// attributes
$elementAttributeService = new AttributeService([], $attributes ?? []);

//
$wrapperTag = TerminStatusEnum::GESTRICHEN->value === $termin['termin_status'] ? ['del'] : [];
?>
<div class="row">
    <div class="col-12 fs-3 fw-light">
        <div class="fs-6 d-flex justify-content-between w-100">
            <div>
                <?= HelperService::format_displayDate(
                    $termin['termin_datum_start'],
                    $termin['termin_datum_ende']
                )  ?>
            </div>
            <?php if ($termin['termin_datum_start'] === $termin['termin_datum_ende']) : ?>
                <div>
                    <?= $this->escape(DTF::format(new DateTime($termin['termin_datum_start']), 'eeee')) ?>
                </div>
            <?php endif ?>
        </div>
        <?php $this->insert('partial::wrappertags', ['type' => 'open', 'tags' => $wrapperTag]); ?>
        <a class="link-body-emphasis text-decoration-none" href="<?= $event_nav ?>?id=<?= $termin['termin_id'] ?>&date=<?= $termin['termin_datum_start'] ?>#<?= $this->escape(HelperService::getAnchorString($termin['termin_datum_start'])) ?>">
            <?= $termin['termin_betreff'] ?>
            <?php if ($termin['termin_mitvon']) : ?>
                (<?= $termin['termin_mitvon'] ?>)
            <?php endif ?>
        </a>
        <?php $this->insert('partial::wrappertags', ['type' => 'close', 'tags' => $wrapperTag]); ?>
    </div>
</div>