<?php

use App\Enum\TerminStatusEnum;
use App\Service\AttributeService;

// init
$terminCollection = $terminCollection;

// attributes
$elementAttributeService = new AttributeService([], $attributes ?? []);

// classes
$wrapperTag = !$terminCollection->current || TerminStatusEnum::GESTRICHEN->value === $terminCollection->current['termin_status'] ? ['del'] : [];
?>
<div class="<?= $elementAttributeService->getAttrValue('class') ?>">
    <?php $this->insert('partial::wrappertags', ['type' => 'open', 'tags' => $wrapperTag]); ?>
    <p class="fw-light">
        <?php if ($terminCollection->current['_def_neu_infobox']) : ?>
            <span class="badge bg-warning-subtle text-warning-emphasis fw-bold me-1">Neu</span>
        <?php elseif ($terminCollection->current['_def_updated_infobox']) : ?>
            <span class="badge bg-warning-subtle text-warning-emphasis fw-bold me-1">Aktualisiert</span>
        <?php endif; ?>
        <?= $this->escape($terminCollection->current['termin_betreff']) ?>
        <?php if ($terminCollection->current['termin_mitvon']) : ?>
            <br>
            <?= $this->escape($terminCollection->current['termin_mitvon']) ?>
        <?php endif ?>
    </p>
    <?php if ($terminCollection->current['termin_label'] || $terminCollection->current['termin_link']): ?>
        <p class="fw-light">
            <?php if ($terminCollection->current['termin_label']) : ?>
                <?= $this->escape($terminCollection->current['termin_label']) ?>
            <?php endif; ?>
            <?php if ($terminCollection->current['termin_link']) : ?>
                <a class="icon-link d-block text-decoration-none" href="<?= $this->escape($terminCollection->current['termin_link']) ?>">
                    <i class="bi bi-link"></i> <?= $this->escape($terminCollection->current['termin_link_titel'] ?? 'Link') ?>
                </a>
            <?php endif ?>
        </p>
    <?php endif; ?>
    <?php $this->insert('partial::wrappertags', ['type' => 'close', 'tags' => $wrapperTag]); ?>
</div>