<?php $this->layout('layout::default', ['title' => 'EGLi (Manage) - Termine ']) ?>
<?php $this->push('stylesheet') ?>
<link href="/css/app/def-termin-grid.css?u=<?= REFRESH_STATIC_FILES ?>" rel="stylesheet">
<?php $this->end() ?>
<?php $this->push('javascript') ?>
<script defer src="/js/app/def-termin-grid.js?u=<?= REFRESH_STATIC_FILES ?>" type="module"></script>
<?php $this->end() ?>
<!-- nav -->
<nav class="navbar navbar-dark bg-primary mb-3">
    <div class="container-fluid">
        <a class="navbar-brand fw-bold" href="/manage/home-read">Home</a>
        <a class="navbar-brand fw-bold" href="/">Ansicht</a>
        <a class="navbar-brand fw-bold" href="/manage/media-read">Media</a>
        <a class="navbar-brand fw-bold" href="/cleanup">Cleanup</a>
        <a class="navbar-brand fw-bold" href="/app-logout">Abmelden</a>
    </div>
</nav>
<?php $this->insert('app-partial::___grid___calender', [
    'data' => $terminCollection,
    'terminIdParam' => $terminIdParam,
    'dateParam' => $dateParam,
    'loggedIn' => isset($this->data['security']) ? $this->data['security']->getIdentity() : false,
    'prevnextUrl' => '/manage/termin-grid',
    'searchUrl' => '/manage/termin-search',
]) ?>