<!DOCTYPE html>
<html lang="de" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= $this->section('meta') ?>
    <title><?= $this->e($title) ?></title>
    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="/css/main.css?u=<?= REFRESH_STATIC_FILES ?>" rel="stylesheet">
    <?= $this->section('stylesheet') ?>
    <!-- JavaScript -->
    <script>
        let theme = (new URL(document.location)).searchParams.get("theme");
        if ('light' === theme || 'dark' === theme) {
            sessionStorage.setItem('theme', theme);
        } else if (!sessionStorage.getItem('theme')) {
            if (window.matchMedia('(prefers-color-scheme: dark)').matches)
                sessionStorage.setItem('theme', 'dark');
            else
                sessionStorage.setItem('theme', 'light');
        }
        document.documentElement.setAttribute('data-bs-theme', sessionStorage.getItem('theme'));
    </script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body data-page-datetime="<?= date("Y-m-d-H-i-s") ?>">
<?= $this->section('content') ?>
<!-- scrollup button -->
<button class="corner_button" onclick="topFunction()" id="top_corner_button" title="Go to top">
    <i class="bi bi-caret-up-fill"></i>
</button>
<!-- flash messages -->
<?php if (isset($notifications)) : ?>
    <?php $this->insert('partial::flash') ?>
<?php endif; ?>
<script src="/js/main.js?u=<?= REFRESH_STATIC_FILES ?>"></script>
<?= $this->section('javascript') ?>
</body>
</html>