<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */

declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Handler\Home\DefAppCleanupHandler::class     => App\Handler\Home\DefAppCleanupHandlerFactory::class,
            App\Handler\Auth\DefAppLoginHandler::class       => App\Handler\Auth\DefAppLoginHandlerFactory::class,
            App\Handler\Auth\DefAppLogoutHandler::class      => App\Handler\Auth\DefAppLogoutHandlerFactory::class,
            App\Handler\Termin\DefTerminIcsHandler::class    => App\Handler\Termin\DefTerminIcsHandlerFactory::class,
            App\Handler\Media\DefMediaIndexHandler::class    => App\Handler\Media\DefMediaIndexHandlerFactory::class,
            App\Handler\Termin\DefTerminShowHandler::class   => App\Handler\Termin\DefTerminShowHandlerFactory::class,
            App\Handler\Termin\DefTerminHowtoHandler::class  => App\Handler\Termin\DefTerminHowtoHandlerFactory::class,
            App\Handler\Termin\DefTerminIndexHandler::class  => App\Handler\Termin\DefTerminIndexHandlerFactory::class,
            App\Handler\Termin\DefTerminMonthHandler::class  => App\Handler\Termin\DefTerminMonthHandlerFactory::class,
            App\Middleware\HistoryMiddleware::class          => App\Middleware\HistoryMiddlewareFactory::class,
            App\Middleware\RedirectMiddleware::class         => App\Middleware\RedirectMiddlewareFactory::class,
            App\Middleware\ServerCacheMiddleware::class      => App\Middleware\ServerCacheMiddlewareFactory::class,
            App\Middleware\TemplateDefaultsMiddleware::class => App\Middleware\TemplateDefaultsMiddlewareFactory::class,
            App\Page\Home\MngHomeReadPage::class             => App\Page\Home\MngHomeReadPageFactory::class,
            App\Page\Media\MngMediaReadPage::class           => App\Page\Media\MngMediaReadPageFactory::class,
            App\Page\Media\MngMediaWritePage::class          => App\Page\Media\MngMediaWritePageFactory::class,
            App\Page\Termin\MngTerminReadPage::class         => App\Page\Termin\MngTerminReadPageFactory::class,
            App\Page\Termin\MngTerminWritePage::class        => App\Page\Termin\MngTerminWritePageFactory::class,
        ],
    ],
];
